config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :articles do
    resources :comments
  end
  
  concern :the_role, TheRole::AdminRoutes.new
  
  namespace :admin do
    concerns :the_role
  end
  
  get 'about', to: 'main#about'
  get 'users', to: 'users#index'

  root 'articles#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  belongs_to :user
  validates :title, presence: true, 
                    length: { minimum: 5 }
  validates :text, presence: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  belongs_to :user
end

app/models/role.rb
class Role < ActiveRecord::Base
  acts_as_role
end

app/models/user.rb
class User < ActiveRecord::Base
  include TheRole::User
  
  attr_accessor :login
  
  has_many :articles
  has_many :comments
  
  validates :username,
    :uniqueness => {
    :case_sensitive => false
    }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :authentication_keys => [:login]
  
  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include TheRole::Controller
  before_filter :configure_permitted_parameters, if: :devise_controller?
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def access_denied
    flash[:error] = t('the_role.access_denied')
    redirect_to(:back)
  end
  
  protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me, :last_name, :first_name) }
      devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
      devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password, :last_name, :first_name) }
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_filter :authenticate_user!, except: [:index, :show]

  def new
    @article = Article.new
  end
  def index
    @articles = Article.order('created_at DESC').page(params[:page]).per(3)
  end
  def show
    @article = Article.find(params[:id])
  end
  def edit
    @article = Article.find(params[:id])
  end
  
  
  def create
    @article = Article.new(article_params)
    @article.user = current_user
    
    if @article.save 
      redirect_to @article
    else
      render 'new'
    end
  end
  
  def update
    @article = Article.find(params[:id])
    if current_user.owner?( @article )
      if @article.update(article_params)
        redirect_to @article
      else
        render 'edit'
      end
    end
  end

  def destroy
    @article = Article.find(params[:id])
    if current_user.owner?(@article)
      @article.destroy
    end
    
    redirect_to articles_path
  end  
    
  private
    def article_params
      params.require(:article).permit(:title, :text)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_filter :authenticate_user!
  
  def create
    @article = Article.find(params[:article_id])
    @comment = Comment.new(comment_params.merge article: @article)
    @comment.user = current_user
    
    @comment.save 
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    if current_user.owner?(@comment)
      @comment.destroy
    end
    redirect_to article_path(@article)
  end
 
  private
    def comment_params
      params.require(:comment).permit(:body)
    end

end

app/controllers/main_controller.rb
class MainController < ApplicationController

  def about
  end  
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.page(params[:page]).per(10)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
  <% if @article.errors.any? %>
    <div id="error explanation">
      <h2><%= pluralize( @article.errors.count, "error" ) %> prohibited this article from being saved:</h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %>
    <%= f.text_area :text %>
  </p>
  <%= f.hidden_field :user_id %>
  <p>
    <%= f.submit %>
  </p>
  
<% end %>

app/views/articles/edit.html.erb
<h1> Editing article </h1>

<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<% @articles.each do |article| %>
  <p>
    <h2><%= link_to article.title, article_path(article) %></h2>
    <p>
      <i>by <%= article.user.first_name %> <%= article.user.last_name %></i><br>
      <%= article.created_at.to_s(:short) %>
    </p>
    <p>
      <%= truncate article.text, length: 80 %>
      <%= link_to "Show full article", article_path(article) %>
    </p>
    <% if user_signed_in? %>
      <% if current_user.owner?(article) %>
          <%= link_to "Edit", edit_article_path(article) %>
          <%= link_to 'Delete', article_path(article), method: :delete, data: { confirm: 'Are you sure?' } %><br />
      <% end %>
    <% end %>
  </p>
<% end %>
<%= paginate @articles %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>
  

app/views/articles/show.html.erb
<ul class="articles">
  <p>
    <h2><%= link_to @article.title, article_path(@article) %></h2>
    <i>by <%= @article.user.first_name %> <%= @article.user.last_name %></i> <%= @article.created_at.to_s(:short) %>
    <p>
      <%= @article.text %>
    </p>
    <% if user_signed_in? %>
      <% if current_user.owner?(@article) %>
          <%= link_to "Edit", edit_article_path(@article) %>
          <%= link_to 'Delete', article_path(@article), method: :delete, data: { confirm: 'Are you sure?' } %><br />
      <% end %>
      <p>
      <h2>Comments</h2>
      <%= render @article.comments %>
      Add a comment:
      <%= render "comments/form" %>
      </p>

      <%= link_to 'Back', articles_path %><br />
    <% end %>
  </li>
  </p>
</ul>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= mail_to comment.user.email, comment.user.username %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
  <% if current_user.owner? comment %>
  <%= link_to 'Destroy Comment', [comment.article, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
  <% end %>
</p>
<br />

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
  <p>
    <%= f.text_area :body %>
  </p>
  <%= f.hidden_field :user_id %>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/_panel.html.erb
<div id="user_nav">
  <% if user_signed_in? %>
    <p>
      Signed in as <%= current_user.email %>.<br />
      <%= link_to "Sign out", destroy_user_session_path, method: :delete %> <br />
    </p>
    <p>
      <%= link_to "Edit your profile", edit_user_registration_path %><br />
      <%= link_to "Create new article", new_article_path %>
    </p>
  <% else %>
    <%= link_to "Register", new_user_registration_path %> or 
    <%= link_to "Log in", new_user_session_path %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Blog" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">My simple blog</a>
          <div class="nav-collapse">
            <ul class="nav">
              <li><%= link_to "Home", root_path %></li>
              <li><%= link_to "About blog", about_path %></li>
              <li><%= link_to "Users", users_path %></li>
            </ul>
          </div>
        </div>
      </div>
    </div>


  
    <div class="row2">
      <div class="span9"><%= yield %></div>
      <div class="span3">
          <h2>User panel</h2>
          <p><%= render 'layouts/panel' %></p>        
        </div>
      </div>
    </div> <!-- /container -->

  </body>
</html>

app/views/main/about.html.erb
<h2>About blog</h2>
A simple blog in RoR. Users are able to write articles and comments. 

app/views/users/index.html.erb
<table class="table table-condensed">
  <tr>
    <th>Username</th>
    <th>First name</th>
    <th>Last name</th>
    <th>Email</th>
  </tr>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.username %></td>
      <td><%= user.first_name %></td>
      <td><%= user.last_name %></td>
      <td><%= user.email %></td>
    </tr>
  <% end %>
</table>
<%= paginate @users %>